# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'postgres/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'package'

- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP 4.7 RHPDS'
    cmd: 'oc new-project open-liberty-demo'
    ignoreFlag: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP 4.7 RHPDS'
    cmd: 'project open-liberty-demo'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP 4.7 RHPDS'
    cmd: 'new-build open-liberty --name=aro-cafe-postgres --binary=true'
    ignoreFlag: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP 4.7 RHPDS'
    cmd: 'start-build --from-dir=apply -f ${SYSTEM_DEFAULTWORKINGDIRECTORY}/postgres --follow aro-cafe-postgres'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP 4.7 RHPDS'
    cmd: 'create -f db-secret'

- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP 4.7 RHPDS'
    cmd: 'oc create -f ${SYSTEM_DEFAULTWORKINGDIRECTORY}/openlibertyapplication-postgres.yaml'
