apiVersion: v1
kind: Secret
metadata:
  # - replace "postgres" with "mssql" for testing DB connection with Azure SQL
  # - replace "postgres" with "postgres" for testing DB connection with Azure Database for PostgreSQL
  name: db-secret-postgres
  namespace: open-liberty-demo 
type: Opaque
stringData:
  db.server.name: database.sample-liberty
  db.port.number: "5432"
  db.name: postgres
  db.user: postgres
  db.password: postgres
  db.ssl: "false"
